
create or replace TRIGGER TR_MATRICULA
 before 
 INSERT ON MATRICULAACTIVIDAD 
 FOR EACH ROW
 declare
 PRECIO NUMBER(7,2);
 cursor Matricula is select FK_ID_ACTIVIDAD FROM MATRICULAACTIVIDAD 
 WHERE FK_CEDULANINIO = :NEW.FK_CEDULANINIO and FK_ID_ACTIVIDAD = :NEW.FK_ID_ACTIVIDAD;
 BEGIN 
 SELECT PRECIO_ACTIVIDAD INTO PRECIO FROM ACTIVIDAD WHERE ID_ACTIVIDAD = :NEW.FK_ID_ACTIVIDAD;
 :new.TOTALPAGAR:=PRECIO;
 DBMS_OUTPUT.put_line ('SE ACTUALIZO VALOR A PAGAR');
 for registros in Matricula loop
  IF(registros.FK_ID_ACTIVIDAD=:NEW.FK_ID_ACTIVIDAD)THEN
     :new.TOTALPAGAR:= PRECIO/2;
     DBMS_OUTPUT.put_line ('POR REPETIR MATRICULA SE APLICO 50% DE DESCUENTO');   
  END IF;
 end loop;
 END TR_MATRICULA;